/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public boolean canTakeExam(int attendance) {
        return attendance >= 75;
    }

    public boolean isEligibleForDiscount(int age) {
        return age > 18;
    }

    public int divide(int a, int b) {
        return a / b;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
